spring:
  datasource:
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  flyway:
    enabled: false
