spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsup
    username: whatsup
    password: whatsup
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
